# 

![](https://datasciencebocconi.github.io/Images/Other/logoBocconi.png)

# Preliminaries

In [1]:
# Loading the necessary libraries
import pandas as pd
import re
import nltk

## String manipulation

In [2]:
monty = 'Monty Python'
monty

'Monty Python'

In [3]:
circus = "Monty Python's Flying Circus"
circus

"Monty Python's Flying Circus"

In [4]:
circus = 'Monty Python\'s Flying Circus'
circus

"Monty Python's Flying Circus"

In [5]:
'very' + 'very' + 'very'
'very' * 3

'veryveryvery'

### Exercise

Try running the following code, then try to use your understanding of
the string `+` and `*` operations to figure out how it works. Be careful
to distinguish between the string `' '`,which is a single white-space
character, and `''`, which is the empty string.

``` python
a = [1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1]
b = [' ' * 2 * (7 - i) + 'python' * i for i in a]

print(b)
```

    ['            python', '          pythonpython', '        pythonpythonpython', '      pythonpythonpythonpython', '    pythonpythonpythonpythonpython', '  pythonpythonpythonpythonpythonpython', 'pythonpythonpythonpythonpythonpythonpython', '  pythonpythonpythonpythonpythonpython', '    pythonpythonpythonpythonpython', '      pythonpythonpythonpython', '        pythonpythonpython', '          pythonpython', '            python']

## Regular expressions

<https://regexr.com>

# Text mining

## The IMDB dataset

assd

#### Description

n asdad

#### Import the data

In [7]:
# Let us import the dataset (it requires some time)
imdb = pd.read_csv('https://datasciencebocconi.github.io/Data/IMDB_reviews.csv')
print(imdb.shape) # Size of the dataset

(50000, 1)

In [8]:
# Display the first 10 rows of this dataset
imdb.head(10)

,review
0,One of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...
2,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is..."
5,"Probably my all-time favorite movie, a story o..."
6,I sure would like to see a resurrection of a u...
7,"This show was an amazing, fresh & innovative i..."
8,Encouraged by the positive comments about this...
9,If you like original gut wrenching laughter yo...

## Data cleaning

In [9]:
# Let us have a look at a random review, say the 144th
review = imdb.iloc[143, 0]
review

"This cute animated short features two comic icons - Betty Boop and Henry.<br /><br />Henry is the bald, slightly portly boy from the comics who never speaks.<br /><br />Well here he does speak!<br /><br />He wants to get a puppy from Betty Boop's pet store, and when he is left to mind the store - some hilarious hijinks ensue.<br /><br />Betty sings a song about pets, Henry gets in a battle with birds and a monkey, but everything works out in the end."

#### Removing the HTML code

In [10]:
# Removes the <br /> tag
re.sub(r"<br />", " ", review)

"This cute animated short features two comic icons - Betty Boop and Henry.  Henry is the bald, slightly portly boy from the comics who never speaks.  Well here he does speak!  He wants to get a puppy from Betty Boop's pet store, and when he is left to mind the store - some hilarious hijinks ensue.  Betty sings a song about pets, Henry gets in a battle with birds and a monkey, but everything works out in the end."

[BeautifulSoup
documentation](https://beautiful-soup-4.readthedocs.io/en/latest/)

In [11]:
from bs4 import BeautifulSoup

# Removes the <br />
def remove_html(data):
    data = BeautifulSoup(data)
    return data.getText()

In [12]:
review = remove_html(review)
review

"This cute animated short features two comic icons - Betty Boop and Henry.Henry is the bald, slightly portly boy from the comics who never speaks.Well here he does speak!He wants to get a puppy from Betty Boop's pet store, and when he is left to mind the store - some hilarious hijinks ensue.Betty sings a song about pets, Henry gets in a battle with birds and a monkey, but everything works out in the end."

#### Remove punctuation and special symbols

In [13]:
def remove_symb(data):
    data = re.sub(r'[^\w\s]', " ", data)
    return data

In [14]:
review = remove_symb(review)
print(review)

This cute animated short features two comic icons   Betty Boop and Henry Henry is the bald  slightly portly boy from the comics who never speaks Well here he does speak He wants to get a puppy from Betty Boop s pet store  and when he is left to mind the store   some hilarious hijinks ensue Betty sings a song about pets  Henry gets in a battle with birds and a monkey  but everything works out in the end

#### Stopwords

In [15]:
from nltk.corpus import stopwords
# stopwords.words('english')

In [16]:
# [w for w in nltk.word_tokenize(review) if w not in stopwords.words('english')]

## Denoise the whole dataset

In [17]:
# This will take some time
imdb['review'] = imdb['review'].apply(lambda z: remove_html(z))
imdb.head(10)

,review
0,One of the other reviewers has mentioned that ...
1,A wonderful little production. The filming tec...
2,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is..."
5,"Probably my all-time favorite movie, a story o..."
6,I sure would like to see a resurrection of a u...
7,"This show was an amazing, fresh & innovative i..."
8,Encouraged by the positive comments about this...
9,If you like original gut wrenching laughter yo...

## Stopwords